allowBuilds:
  "@google/genai": true
  '@vscode/ripgrep': true
  esbuild: true
  koffi: true
  lefthook: true
  protobufjs: true
patchedDependencies:
  '@morphllm/morphsdk@0.2.171': patches/@morphllm__morphsdk@0.2.171.patch
